blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
imports_granularity = "Item"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
wrap_comments = true
